apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.kubeTally.postgresSecretName }}
  namespace: kubeslice-controller
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
type: Opaque
data:
  postgresUser: {{ .Values.global.kubeTally.postgresUser | b64enc }}  # Base64-encoded PostgreSQL username
  postgresPassword: {{ .Values.global.kubeTally.postgresPassword | b64enc }}  # Base64-encoded PostgreSQL password
  postgresAddr: {{ .Values.global.kubeTally.postgresAddr | b64enc }}  # Base64-encoded PostgreSQL address
  postgresPort: {{ .Values.global.kubeTally.postgresPort | toString | b64enc }}  # Base64-encoded PostgreSQL port
  postgresDB: {{ .Values.global.kubeTally.postgresDB | b64enc }}  # Base64-encoded PostgreSQL database name
  postgresSslmode: {{ .Values.global.kubeTally.postgresSslmode | b64enc }}
