operator:
  image: worker-operator-ent
  tag: 1.15.0
  pullPolicy: IfNotPresent
  logLevel: INFO
  excludeNamespaces:
  - "kube-system"
  - "default"
  - "kubeslice-controller"
  - "kubeslice-system"
  - "kube-node-lease"
  - "kube-public"
  - "istio-system"

controllerSecretName: kubeslice-hub #default name used if not specify any name
## Base64 encoded secret values from controller cluster
controllerSecret:
  namespace:
  endpoint:
  ca.crt:
  token:

cluster:
  name:
  nodeIp: # This field is deprecated. You can set nodeIPs through cluster spec.
  endpoint:

workerInstaller:
  image: worker-installer
  tag: 1.5.0
  
events:
  disabled: false

metrics:
  insecure: false
  metricResolution: "15s"
  imagePullPolicy: IfNotPresent

imagePullSecretsName: "kubeslice-image-pull-secret"
# leave the below fields empty if secrets are managed externally.
imagePullSecrets:
  repository: https://index.docker.io/v1/ ## Value to be used incase using the docker hub images-  https://index.docker.io/v1/
  username:
  password:
  email:
  dockerconfigjson: ## Value to be used if using external secret managers

controllerNamespace: kubeslice-controller

global:
  imageRegistry: docker.io/aveshasystems
  profile:
    openshift: false
